# Tests that the docker container builds and runs on Windows and macOS
name: Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci --production
      - name: Build Container
        run: make docker
      - name: Saucectl Run
        run: bash ./tests/integration/integration.sh

