name: Docker Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saucelabs/stt-cypress-mocha-node
          tag_with_ref: true
          cache_froms: saucelabs/stt-cypress-mocha-node:latest
          push: false
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: docker pull --platform linux node
        name: Pull Docker linux
      - run: make docker
        name: Build Container
      - uses: actions/checkout@v2
        with:
          repository: saucelabs/saucectl
          path: saucectl
          ref: dpgraham-windows-macos-ci-exception
      - run: |
          pushd saucectl && make build && popd
          ./saucectl/saucectl run --config ./tests/config-tests/sauce-config.yml # TODO: Make this a bash script that runs them all
        