name: Docker Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saucelabs/stt-cypress-mocha-node
          tag_with_ref: true
          cache_froms: saucelabs/stt-cypress-mocha-node:latest
          push: false
      - uses: actions/checkout@v2
        with:
          repository: saucelabs/saucectl
          path: saucectl
          ref: dpgraham-windows-macos-ci-exception
        env:
          SKIP_CI: true
      - run: |
          pushd saucectl && make build && popd
          ./saucectl/saucectl run --config ./tests/e2e/typescript-sauce-config.yml # TODO: Make this a bash script that runs them all
        env:
          SKIP_CI: true
        