name: Docker Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: ls
        run: pwd
      -
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saucelabs/stt-cypress-mocha-node
          tag_with_ref: true
          cache_froms: saucelabs/stt-cypress-mocha-node:latest
          push: false
      
      # Checkout the latest saucectl
      - uses: actions/checkout@v2
        with:
          repository: saucelabs/saucectl
          path: saucectl

      # Node/NPM dependency
      - name: Use Node.JS 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci

      # Fix permissions problem
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home
      
      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      # Build SauceCtl and run it
      - run: |
          make docker
          pushd saucectl && make build && popd
          npm run e2e:docker
        env:
          SKIP_CI: true
          SAUCE_CTL_BINARY: ./saucectl/saucectl
        name: Build SauceCtl and run
  build-ubuntu-bundle-and-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/
  build-windows-bundle-and-test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/
